debug: false
server:
  port: 8090
  context-path: /
spring:
  session:
    store-type: none
  http:
    encoding:
      charset: utf-8
  aop:
    auto: true
#  thymeleaf:
#    mode: HTML5
#    encoding: utf-8
#    content-type: text/html
#    cache: false
#  view:
#    prefix: /WEB-INF/jsp/
#    suffix: .jsp
  mvc:
    view:
      prefix: /WEB-INF/jsp/
#      suffix: .jsp
#    servlet:
#      load-on-startup: 1
  redis:
    host: 127.0.0.1
    port: 6379
#    password: FNFl9F2O2Skb8yoKM0jhHA==
    timeout: 10000
    pool:
      max-active: 500
      max-idle: 5
      max-wait: 10000
dubbo:
  scan: cn.ts.web.upms
  application:
    name: ts-web-upms
  protocol:
    name: dubbo
    port: 20802
  registry:
#    check: false
#    address: multicast://224.0.0.0:1112
    address: zookeeper://127.0.0.1:2181
    file: E:\\Export\\webapps\\${spring.dubbo.application.name}.${spring.dubbo.protocol.name}.${spring.dubbo.protocol.port}.cache